# Generated by Django 4.2.18 on 2025-02-23 20:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='ImagesCategories/')),
                ('dateAjout', models.DateTimeField(auto_now_add=True)),
                ('dateModification', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-dateAjout'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomClient', models.CharField(max_length=128)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format international (+123456789)', regex='^\\+?1?\\d{9,15}$')])),
                ('dateInscription', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-dateInscription'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFacture', models.DateTimeField(auto_now_add=True)),
                ('montantFacture', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('statut', models.CharField(blank=True, choices=[('Regle', 'Réglé'), ('Non_Regle', 'Non Régle')], default='Non_Regle', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format international (+123456789)', regex='^\\+?1?\\d{9,15}$')])),
                ('operateur', models.CharField(choices=[('Moov', 'Moov'), ('Yas', 'Yas')])),
                ('operation', models.CharField(choices=[('Retrait', 'Retrait'), ('Depot', 'Dépot')])),
                ('montant', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('dateTransaction', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('valide', models.BooleanField(default=False)),
                ('totalAchat', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to='GestionProduits.client')),
            ],
            options={
                'ordering': ['-dateCreation'],
            },
        ),
        migrations.CreateModel(
            name='ModePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyen', models.CharField(choices=[('Espece', 'Espèces'), ('Flooz', 'Flooz'), ('Mix by Yas', 'Mix by Yas'), ('Cheque_Bancaire', 'Chèque Bancaire')], default='Espèce')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('datePaiement', models.DateTimeField(auto_now_add=True, null=True)),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='GestionProduits.facture')),
            ],
        ),
        migrations.AddField(
            model_name='facture',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='GestionProduits.panier'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('stock', models.PositiveBigIntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagesArticles/')),
                ('prixUnitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateAjout', models.DateTimeField(auto_now_add=True)),
                ('dateModification', models.DateTimeField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='GestionProduits.categorie')),
            ],
            options={
                'ordering': ['-dateAjout'],
            },
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCommande', models.DateTimeField(auto_now_add=True)),
                ('quantite', models.PositiveBigIntegerField(default=1)),
                ('prixAchat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achat', to='GestionProduits.article')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achatClient', to='GestionProduits.panier')),
            ],
            options={
                'ordering': ['-dateCommande'],
            },
        ),
    ]
