# Generated by Django 4.2.18 on 2025-02-07 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProduits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='dateModification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='dateModification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=False)),
                ('totalAchat', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to='GestionProduits.client')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCommande', models.DateTimeField(auto_now_add=True)),
                ('quantite', models.PositiveBigIntegerField(default=1)),
                ('prixAchat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achat', to='GestionProduits.article')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achatClient', to='GestionProduits.panier')),
            ],
            options={
                'ordering': ['dateCommande'],
            },
        ),
    ]
