# Generated by Django 4.2.18 on 2025-02-11 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProduits', '0002_alter_article_datemodification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format international (+123456789)', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
