# Generated by Django 4.2.18 on 2025-02-12 22:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProduits', '0003_alter_client_telephone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achat',
            options={'ordering': ['-dateCommande']},
        ),
        migrations.AddField(
            model_name='panier',
            name='NouveauTelephoneClient',
            field=models.CharField(blank=True, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format international (+123456789)', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='panier',
            name='NouveautNomClient',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='GestionProduits.categorie'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to='GestionProduits.client'),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('prixTotalAchat', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('statut', models.BooleanField(default=False)),
                ('dateFacture', models.DateTimeField(auto_now_add=True)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='GestionProduits.panier')),
            ],
        ),
    ]
