# Generated by Django 4.2.18 on 2025-02-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProduits', '0004_alter_achat_options_panier_nouveautelephoneclient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-dateInscription']},
        ),
        migrations.AlterModelOptions(
            name='panier',
            options={'ordering': ['-dateCreation']},
        ),
    ]
