# Generated by Django 4.2.18 on 2025-02-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProduits', '0005_alter_client_options_alter_panier_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panier',
            old_name='NouveautNomClient',
            new_name='NouveauNomClient',
        ),
    ]
