# Generated by Django 4.2.18 on 2025-02-14 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProduits', '0006_rename_nouveautnomclient_panier_nouveaunomclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='NouveauNomClient',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='NouveauTelephoneClient',
        ),
    ]
