# Generated by Django 4.2.18 on 2025-02-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProduits', '0009_alter_transactions_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Espèce', 'Espèce'), ('Flooz', 'Flooz'), ('Mix by Yas', 'Mix by Yas')], default='Espèce')),
            ],
        ),
        migrations.AddField(
            model_name='panier',
            name='numero',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
