# Generated by Django 4.2.18 on 2025-02-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProduits', '0010_modepaiement_panier_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='prixTotalAchat',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='statut',
        ),
        migrations.AddField(
            model_name='facture',
            name='etat',
            field=models.CharField(blank=True, choices=[('Réglé', 'Réglé'), ('Non Régle', 'Non Régle')], default='Non Réglé', null=True),
        ),
        migrations.AlterField(
            model_name='modepaiement',
            name='type',
            field=models.CharField(choices=[('Espèce', 'Espèce'), ('Flooz', 'Flooz'), ('Mix by Yas', 'Mix by Yas'), ('Non régle', 'Non régle')], default='Espèce'),
        ),
    ]
