# Generated by Django 4.2.18 on 2025-02-18 21:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProduits', '0011_remove_facture_numero_remove_facture_prixtotalachat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='modepaiement',
            name='type',
        ),
        migrations.AddField(
            model_name='facture',
            name='montantFacture',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='statut',
            field=models.CharField(blank=True, choices=[('Regle', 'Réglé'), ('Non_Regle', 'Non Régle')], default='Non_Regle', null=True),
        ),
        migrations.AddField(
            model_name='modepaiement',
            name='datePaiement',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 18, 21, 15, 42, 945721)),
        ),
        migrations.AddField(
            model_name='modepaiement',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='GestionProduits.facture'),
        ),
        migrations.AddField(
            model_name='modepaiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='modepaiement',
            name='moyen',
            field=models.CharField(choices=[('Espece', 'Espèces'), ('Flooz', 'Flooz'), ('Mix by Yas', 'Mix by Yas'), ('Cheque_Bancaire', 'Chèque Bancaire')], default='Espèce'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='operation',
            field=models.CharField(choices=[('Retrait', 'Retrait'), ('Depot', 'Dépot')]),
        ),
    ]
