# Generated by Django 4.2.18 on 2025-02-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProduits', '0012_remove_facture_etat_remove_modepaiement_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modepaiement',
            name='datePaiement',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
